server:
  port: 8082

spring:
  application:
    name: auth-service
  cloud:
    config:
      fail-fast: false
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 10s
        enabled: true
        register: true
        prefer-ip-address: true
        ip-address: 127.0.0.1
  keycloak:
    server-url: ${keycloak.server-url:http://localhost:9090}
    realm: ${keycloak.realm:docunexa}
    client-id: ${keycloak.client-id:gateway-client}
    client-secret: ${keycloak.client-secret}
    admin-client-id: ${keycloak.admin-client-id:admin-cli}
    admin-username: ${keycloak.admin-username:admin}
    admin-password: ${keycloak.admin-password:admin}
  app:
    redirect-uri: http://localhost:8080
  user-service:
    url: http://localhost:8081
  mail:
    host: ${smtp.host:smtp.gmail.com}
    port: ${smtp.port:587}
    username: ${smtp.user:ddigimor@gmail.com}
    password: ${smtp.password:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          from: ${smtp.from:ddigimor@gmail.com}
          from-display-name: ${smtp.from-display-name:Docunexa}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.vault: DEBUG
    org.springframework.cloud.vault: DEBUG