server:
  port: 8082

spring:
  application:
    name: auth-service
  config:
    import: "vault://"
  cloud:
    vault:
      uri: http://localhost:8200
      token: ${VAULT_TOKEN:myroot}
      authentication: TOKEN
      kv:
        enabled: true
        backend: secret
        default-context: ${spring.application.name}
        profile-separator: '/'
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 10s
        enabled: true
        register: true
keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}
logging:
  level:
    org.springframework.vault: DEBUG
    org.springframework.cloud.vault: DEBUG
app:
  redirect-uri: http://localhost:8080

user-service:
  url: http://localhost:8081
management:
  endpoints:
    web:
      exposure:
        include: "*"