server:
  port: 8082

spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      fail-fast: false
    consul:
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 15s
        enabled: true
        register: true
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
          default-key-serializer: org.apache.kafka.common.serialization.StringSerializer
          default-value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          auto-create-topics: true
      bindings:
        userEvents-out-0:
          destination: user-events
          content-type: application/json
          producer:
            partition-key-expression: payload.aggregateId
            required-groups: user-service

  keycloak:
    server-url: ${keycloak.server-url}
    realm: ${keycloak.realm}
    client-id: ${keycloak.client-id}
    client-secret: ${keycloak.client-secret}
    admin-client-id: ${keycloak.admin-client-id}
    admin-username: ${keycloak.admin-username}
    admin-password: ${keycloak.admin-password}
  app:
    redirect-uri: ${app.redirect-uri}
  user-service:
    url: http://localhost:8081

kafka:
  topic:
    user-events: user-events

management:
  endpoints:
    web:
      exposure:
        include: "*"