#server:
#  port: 8083
#
#file:
#  upload-dir: uploads
#
#spring:
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/docunexa_document_db
#    username: postgres
#    password: postgres
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#
#    show-sql: true
#
#    properties:
#      hibernate:
#        format_sql: true
#
#  servlet:
#    multipart:
#      max-file-size: 20MB
#      max-request-size: 20MB
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#  endpoint:
#    health:
#      show-details: always
#
#  health:
#    rabbit:
#      enabled: false


server:
  port: 8083

file:
  upload-dir: uploads

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/docunexa_document_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB