server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/docunexa_document_db
    username: ${db.username}
    password: ${db.password}

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  cloud:
    vault:
      enabled: true
      uri: http://localhost:8201
      token: myroot
      authentication: TOKEN
      kv:
        enabled: true
        backend: secret
        default-context: document-service

    stream:
      kafka:
        binder:
          brokers: localhost:9092

      bindings:
        documentEvents-out-0:
          destination: document-events
          content-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  health:
    rabbit:
      enabled: false

    vault:
      enabled: false

file:
  upload-dir: uploads