spring:
  application:
    name: gateway-service
  cloud:
    config:
      fail-fast: false
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url:http://localhost:9090}/realms/${keycloak.realm:docunexa}

management:
  endpoints:
    web:
      exposure:
        include: "*"