spring:
  application:
    name: gateway-service
  cloud:
    config:
      fail-fast: false
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: ocr-service
          uri: lb://ocr-service
          predicates:
            - Path=/api/ocr/**
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/documents/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}

management:
  endpoints:
    web:
      exposure:
        include: "*"