server:
  port: 8081

spring:
  application:
    name: user-service
  config:
    import: "vault://"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 10s
        enabled: true
        register: true
    vault: 
      uri: http://localhost:8200
      token: ${VAULT_TOKEN:myroot}
      authentication: TOKEN
      kv:
        enabled: true
        backend: secret
        default-context: ${spring.application.name}
        profile-separator: '/'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}
logging:
  level:
    org.springframework.vault: DEBUG
    org.springframework.cloud.vault: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"