server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}

management:
  endpoints:
    web:
      exposure:
        include: "*"