server:
  port: 8081

spring:
  application:
    name: user-service
  cloud:
    config:
      fail-fast: false
    consul:
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 15s
        enabled: true
        register: true
        
  datasource:
    url: ${database.url:jdbc:postgresql://localhost:5432/docunexa-db}
    username: ${database.username:postgres}
    password: ${database.password:}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url:http://localhost:9090}/realms/${keycloak.realm:docunexa}

management:
  endpoints:
    web:
      exposure:
        include: "*"